[DEFAULT]
bind_host = 0.0.0.0
bind_port = 9292
log_dir = /var/log/glance
workers = 2
show_image_direct_url = True

[database]
connection = mysql+pymysql://glance:glancepass@mariadb/glance

[keystone_authtoken]
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = glance
password = glancepass
auth_type = password
memcached_servers = memcached:11211

[paste_deploy]
flavor = keystone

[glance_store]
stores = rbd
default_store = rbd
rbd_store_pool = images
rbd_store_user = glance
rbd_store_ceph_conf = /etc/ceph/ceph.conf
rbd_store_chunk_size = 8
