[DEFAULT]
log_dir = /var/log/keystone

[database]
connection = mysql+pymysql://keystone:keystonepass@mariadb/keystone

[token]
provider = fernet

[fernet_tokens]
key_repository = /etc/keystone/fernet-keys

[credential]
key_repository = /etc/keystone/fernet-keys
