[DEFAULT]
log_dir = /var/log/nova
transport_url = rabbit://guest:guest@rabbitmq:5672/
compute_driver = libvirt.LibvirtDriver
instances_path = /var/lib/nova/instances
use_neutron = True
firewall_driver = nova.virt.firewall.NoopFirewallDriver
enabled_apis = osapi_compute,metadata
osapi_compute_listen = 0.0.0.0
osapi_compute_listen_port = 8774
metadata_listen = 0.0.0.0
metadata_listen_port = 8775
# my_ip written at runtime by nova-compute-start.sh

[api]
auth_strategy = keystone

[keystone_authtoken]
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = nova
password = novapass
auth_type = password
memcached_servers = memcached:11211

[database]
connection = mysql+pymysql://nova:novapass@mariadb/nova

[api_database]
connection = mysql+pymysql://nova:novapass@mariadb/nova_api

[placement]
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = placement
password = placementpass
auth_type = password
region_name = RegionOne

[neutron]
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = neutron
password = neutronpass
auth_type = password
region_name = RegionOne
service_metadata_proxy = True
metadata_proxy_shared_secret = metasecret123

[vnc]
enabled = True
server_listen = 0.0.0.0
server_proxyclient_address = 192.168.20.1
novncproxy_base_url = http://localhost:6080/vnc_lite.html
novncproxy_host = 0.0.0.0
novncproxy_port = 6080

[glance]
api_servers = http://glance:9292

[cinder]
os_region_name = RegionOne
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = cinder
password = cinderpass
auth_type = password

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

[libvirt]
virt_type = kvm
connection_uri = qemu:///system
disk_cachemodes = network=writeback

[scheduler]
discover_hosts_in_cells_interval = 30
