[DEFAULT]
log_dir = /var/log/placement

[api]
auth_strategy = keystone

[keystone_authtoken]
auth_url = http://keystone:5000
project_domain_name = Default
user_domain_name = Default
project_name = service
username = placement
password = placementpass
auth_type = password
memcached_servers = memcached:11211

[placement_database]
connection = mysql+pymysql://placement:placementpass@mariadb/placement
